// <auto-generated />
namespace AptkAma.Sample.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201605171035212_CustomLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
